[project]
name = "deepmt"
version = "0.1.0"
description = "A metamorphic relation automatic generation and hierarchical testing system for deep learning frameworks"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
